// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFBhUJwgB8WIWUYdSQzlzNNV2x16sJB0',
    appId: '1:736961869771:web:bb32988dd99b6593f3284e',
    messagingSenderId: '736961869771',
    projectId: 'astromancygarden-30f3e',
    authDomain: 'astromancygarden-30f3e.firebaseapp.com',
    storageBucket: 'astromancygarden-30f3e.appspot.com',
    measurementId: 'G-Y2F6F7NSNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ3DWUcNegscAOvW1kqQsRq71BjyLqBgo',
    appId: '1:736961869771:android:78ca5c4d09e187daf3284e',
    messagingSenderId: '736961869771',
    projectId: 'astromancygarden-30f3e',
    storageBucket: 'astromancygarden-30f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNCyzR8WZ3L-IRsLZyLWSS0Teo8GMIAg',
    appId: '1:736961869771:ios:439ac294c373f9e6f3284e',
    messagingSenderId: '736961869771',
    projectId: 'astromancygarden-30f3e',
    storageBucket: 'astromancygarden-30f3e.appspot.com',
    iosClientId: '736961869771-tagmslq9h9sppiq1g8ajlco9hc51mm0i.apps.googleusercontent.com',
    iosBundleId: 'com.fisis.fortune.app.fortunetell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNNCyzR8WZ3L-IRsLZyLWSS0Teo8GMIAg',
    appId: '1:736961869771:ios:439ac294c373f9e6f3284e',
    messagingSenderId: '736961869771',
    projectId: 'astromancygarden-30f3e',
    storageBucket: 'astromancygarden-30f3e.appspot.com',
    iosClientId: '736961869771-tagmslq9h9sppiq1g8ajlco9hc51mm0i.apps.googleusercontent.com',
    iosBundleId: 'com.fisis.fortune.app.fortunetell',
  );
}
